// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:to_do_clean_ar/eport.dart';

// Will be generated by dart_mappable
part 'product_model.mapper.dart';

@MappableClass()
class ProductModel extends ProductsEntity with ProductModelMappable {
  const ProductModel({
    required super.category,
    required super.description,
    required super.image,
    required super.price,
    required super.title,
  });
}
